## Check minimum Snakemake version

from snakemake.utils import min_version

min_version("5.20.1")

## Import required libraries
import os

## Configuration file check

if len(config) == 0:
    if os.path.isfile("config/config.yaml"):

        configfile: "config/config.yaml"

    else:
        sys.exit(
            f"Make sure there is a config.yaml file in {os.getcwd()} or specify one with the --configfile commandline parameter."
        )


## Parse config file
# CAN USE CONFIG (config["foo"]) DIRECTLY IN RULES
INPUT_DIR = os.path.normpath(config["INPUT"])
# Dont use script dir but see sourcing in snakefiles and rules section. 
SCRIPTS_DIR = os.path.normpath("workflow/scripts/") # How to call the scripts during modularization?
# Maybe: Non-rule Python statements inside the module are also evaluated in that separate namespace.
# But still will it (the HEAL workflow) have the scripts??? 

## Define number of cores for parsing
count = 0
for item in os.listdir(f"{INPUT_DIR}"):
    item_path = os.path.join(f"{INPUT_DIR}", item)
    # Check if the item is a directory and not excluded
    if os.path.isdir(item_path) and item not in ["bed", "peptide"]:
        count += 1
genespace_parse_threads = count if count < workflow.cores else workflow.cores



## Rules

rule all:
    input:
        genespace_run_log="results/logs/genespace/genespace_run.log" 


rule run_genespace:
    input:
        mc_scan_install_log="results/logs/MCScanX/MScanX_install.log", 
        genespace_run_dir="results/genespace/run_dir",
    params:
        mc_scan_dir="results/genespace/MCScanX/",
    log:
        "results/logs/genespace/genespace_run.log",
    threads:workflow.cores
    conda:
        "envs/genespace.yaml",
    script:
        "scripts/run_genespace.R" 


rule parse_genespace_input:
    input:
        input_dir=f"{INPUT_DIR}",
    output:
        genespace_run_dir=directory("results/genespace/run_dir"),
    params:
        scripts=f"{SCRIPTS_DIR}"
    log:
        "results/logs/genespace/parse_genespace_input.log", # Nothing going it 2> due to agat
    threads:genespace_parse_threads
    conda:
        "envs/genespace.yaml",
    shell: # CAN USE SCRIPTS and associative arrays actually. 
        "bash {params.scripts}/parse_genespace_input.sh -i {input.input_dir} -o {output.genespace_run_dir} -l {log} -c {threads}" 



rule install_MCScanX:
    input:
        mc_scan_dir="results/genespace/MCScanX",
    log:
        "results/logs/MCScanX/MScanX_install.log",
    conda:
        "envs/genespace.yaml",
    shell:
        "make -C {input.mc_scan_dir}" 


rule download_MCScanX:
    output:
        mc_scan_dir=directory("results/genespace/MCScanX"),
    log:
        "results/logs/MCScanX/MCScanX_dowload.log",
    conda:
        "envs/genespace.yaml",
    shell:
        "git clone https://github.com/wyp1125/MCScanX {output.mc_scan_dir}"





